// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rollerDisplayList = lv_roller_create(ui_Screen2);
    lv_obj_set_width(ui_rollerDisplayList, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rollerDisplayList, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rollerDisplayList, LV_ALIGN_CENTER);

    ui_textarea_msg = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_textarea_msg, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_textarea_msg, LV_SIZE_CONTENT);
    lv_obj_set_style_text_font(ui_textarea_msg, &ui_font_tw1616, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_textarea_msg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);//設置文字水平置中
    lv_obj_set_align(ui_textarea_msg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_textarea_msg, LV_OBJ_FLAG_HIDDEN);
}
