// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label_msg;
extern lv_obj_t * ui_Label_msgText;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_rollerDisplayList;
extern lv_obj_t * ui_textarea_msg;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_white_320x240_png);    // assets/White_320x240.png
LV_IMG_DECLARE(ui_img_rgb_320x240_png);    // assets/
LV_IMG_DECLARE(ui_img_red_320x240_png);    // assets/
LV_IMG_DECLARE(ui_img_green_320x240_png);    // assets/
LV_IMG_DECLARE(ui_img_blue_320x240_png);    // assets/
LV_IMG_DECLARE(ui_img_black_320x240_png);    // assets/
LV_IMG_DECLARE(ui_img_689278962);    // assets/
LV_IMG_DECLARE(ui_img_799870042);    // assets/
LV_IMG_DECLARE(ui_img_799871067);    // assets/
LV_IMG_DECLARE(ui_img_799872092);    // assets/

// FONTS
LV_FONT_DECLARE(ui_font_tw1616);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
